# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'FindCVS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FindCVS
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit'

  target 'FindCVSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Stubber'
    pod 'Nimble'
    pod 'RxBlocking'
    pod 'RxTest'
  end
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Apple Silicon Mac용 아키텍처 설정
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386'
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
    
    # 메인 프로젝트에도 동일한 설정 적용
    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386'
          config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
      end
    end
  end

end
